#!/usr/bin/env python3
import re, subprocess

# TODO: add exception for header line

def extract_rssi(line):
    "returns RSSI if the line is a wifi network"
    pattern = ':'.join(['[a-f0-9]{2}']*6)
    reg = re.search(pattern, line)
    try:
        latter = line[reg.end():].split()
        return int(latter[0])
    except:
        return None

def get_airport_s():
    airport_proc = subprocess.Popen('sudo airport -s'.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    try:
        out,err = (text.decode('utf-8') for text in airport_proc.communicate(timeout=10))
    except subprocess.TimeoutExpired:
        airport_proc.kill()
        print('TIMEOUT')
        out,err = (text.decode('utf-8') for text in airport_proc.communicate())
    print(out)
    if err:
        print('ERR:')
        print(err, end='\n\n')
    return out

if __name__ == '__main__':
    airport_s = get_airport_s()
    print('\n\nSORTED')
    network_lines = []
    for line in airport_s.split('\n'):
        rssi = extract_rssi(line)
        if rssi:
            network_lines.append((line, rssi))
    for line in sorted(network_lines, key=lambda l:l[1]):
        print(line[0])
